from __future__ import annotations


RECOMMENDATIONS = {
    "SLA_BREACH": "Verifier la charge, le reseau et les ressources du service concerne.",
    "RESPONSE_TIME_SPIKE": "Verifier la charge, le reseau et les ressources du service concerne.",
    "SERVER_ERROR": "Analyser les logs serveur du producteur et les erreurs applicatives recentes.",
    "TIMEOUT": "Verifier la disponibilite du provider et la configuration des timeouts.",
    "PROVIDER_UNREACHABLE": "Notifier l'equipe responsable du producteur et verifier la connectivite.",
    "ACCESS_DENIED": "Controler les acces, les jetons et les autorisations de l'acteur consommateur.",
    "RATE_LIMIT_EXCEEDED": "Verifier les quotas, le rythme d'appels du consommateur et la configuration de rate limiting.",
    "MISSING_CORRELATION_ID": "Verifier la propagation des identifiants de correlation dans le producteur et le consommateur.",
    "MISSING_LATENCY_METRIC": "Verifier l'instrumentation de latence et le mapping des metriques de l'appel.",
    "DUPLICATE_EVENT": "Verifier l'idempotence du producteur d'evenements et le traitement Kafka du flux concerne.",
    "CORRUPTED_EVENT_PAYLOAD": "Verifier le schema de l'evenement, la serialisation et le contrat de payload.",
    "EVENT_ISOLATION_FOREST_SIGNAL": "Comparer l'evenement avec les appels normaux recents et verifier les variables les plus atypiques.",
    "EVENT_LOF_SIGNAL": "Comparer l'evenement avec son voisinage statistique par API ou flow.",
    "EVENT_AUTOENCODER_SIGNAL": "Analyser les variables responsables de l'erreur de reconstruction sur l'evenement.",
    "LATENCY_SPIKE": "Analyser l'evolution recente des latences et comparer avec les fenetres precedentes.",
    "LATENCY_DRIFT": "Analyser l'evolution recente des latences et identifier une degradation progressive.",
    "GRADUAL_PERFORMANCE_DEGRADATION": "Comparer les fenetres recentes et verifier les ressources du producteur.",
    "SLA_INSTABILITY": "Identifier les periodes de depassement SLA et verifier la stabilite du flow.",
    "TIMEOUT_BURST": "Verifier les timeouts concentres, la connectivite et la disponibilite du producteur.",
    "TRAFFIC_DROP": "Verifier si la chute de trafic est attendue ou si un consommateur ne publie plus.",
    "BUSINESS_HOURS_DEVIATION": "Verifier la legitimite de l'activite hors horaires habituels.",
    "INTERMITTENT_FAILURE": "Comparer les echecs recents avec les logs producteur et les retries.",
    "SERVICE_FLAPPING": "Verifier la disponibilite intermittente du service et les redemarrages recents.",
    "STREAM_PROCESSING_DELAY": "Verifier la latence Kafka, les consommateurs et la chaine d'ingestion.",
    "HIGH_ERROR_RATE": "Investiguer le flux, ses dependances et les erreurs recentes cote producteur.",
    "REPEATED_FAILURES": "Investiguer le flux, ses dependances et les echecs consecutifs.",
    "TRAFFIC_SPIKE": "Verifier si l'activite est legitime ou si elle correspond a un comportement anormal.",
    "PROVIDER_SLOWDOWN": "Verifier la degradation globale du producteur sur plusieurs flux.",
    "SLOW_API_ENDPOINT": "Identifier l'endpoint lent et comparer sa latence avec le SLA attendu.",
    "PARTIAL_PROVIDER_DEGRADATION": "Verifier les flows impactes par le meme producteur et prioriser les plus critiques.",
    "SILENT_FLOW": "Verifier si le consommateur ou le producteur a cesse d'emettre sur ce flow.",
    "TRAFFIC_ASYMMETRY": "Comparer le volume actuel au profil attendu du flow et verifier les appels anormaux.",
    "REPEATED_RETRY_PATTERN": "Analyser les retries et verifier l'idempotence du consommateur.",
    "RARE_FLOW_ACTIVATION": "Confirmer que l'activation du flow est attendue et conforme au programme.",
    "WORKFLOW_SEQUENCE_ANOMALY": "Verifier l'ordre fonctionnel des appels du workflow metier.",
    "CRITICAL_FLOW_INSTABILITY": "Prioriser le flow critique et notifier les equipes responsables.",
    "UNEXPECTED_VOLUME": "Verifier la source du volume anormal et les quotas associes.",
    "QUEUE_PROCESSING_DELAY": "Verifier les files, workers et temps de traitement applicatif.",
    "ABNORMAL_ERROR_AFTER_DEPLOYMENT": "Comparer avec les derniers changements applicatifs ou de configuration.",
    "API_UNDERUSE": "Verifier si la baisse d'utilisation est attendue ou traduit une rupture de consommation.",
    "ML_FLOW_CLUSTER_OUTLIER": "Comparer ce flow aux profils appris et examiner les variables eloignees du cluster.",
    "DL_FLOW_AUTOENCODER": "Analyser les features de flow responsables de l'erreur de reconstruction.",
    "DL_FLOW_SEQUENCE": "Verifier l'evolution successive du profil de flow.",
    "FLOW_SLA_DEGRADATION": "Verifier les appels en depassement SLA et les ressources du flow.",
    "FLOW_LATENCY_DRIFT": "Analyser la progression des latences et comparer les fenetres recentes.",
    "FLOW_ERROR_RATE_SPIKE": "Analyser les erreurs recentes du flow et les logs du producteur.",
    "FLOW_TRAFFIC_DROP": "Verifier une rupture de consommation, de publication ou de routage.",
    "FLOW_TRAFFIC_SPIKE": "Verifier la legitimite de la hausse de trafic et la capacite du service.",
    "FLOW_INTERMITTENT_FAILURES": "Analyser les echecs disperses, les timeouts et les retries du flow.",
    "FLOW_PROVIDER_DEGRADATION": "Verifier le producteur critique et les erreurs serveur affectant le flow.",
    "FLOW_CONSUMER_ABUSE": "Verifier le consommateur dominant, ses quotas et son rythme d'appels.",
    "FLOW_HEALTH_DEGRADATION": "Prioriser le diagnostic du flow car plusieurs indicateurs sont degrades.",
    "CASCADE_FAILURE": "Traiter la dependance amont et identifier les flows propages en priorite.",
    "DEPENDENT_SERVICE_FAILURE": "Verifier le service dependant et ses erreurs recentes.",
    "MULTI_CONSUMER_IMPACT": "Identifier les consommateurs touches et coordonner la communication incident.",
    "SHARED_PROVIDER_FAILURE": "Notifier l'equipe du producteur partage et isoler les flows critiques.",
    "DEPENDENCY_HOTSPOT": "Evaluer la charge du producteur central et les risques de saturation.",
    "CROSS_FLOW_PROPAGATION": "Correller les flows impactes et rechercher une cause commune.",
    "INTEROPERABILITY_DEGRADATION": "Verifier les contrats, SLA et dependances entre systemes GISRE.",
    "SYNCHRONIZED_FAILURE_PATTERN": "Analyser les echecs par minute et chercher un incident partage.",
    "DEPENDENCY_CHAIN_LATENCY": "Tracer la chaine de dependances et identifier le segment lent.",
    "CRITICAL_PROVIDER_INSTABILITY": "Escalader le producteur critique et prioriser les flux a fort impact.",
    "GRAPH_CONNECTIVITY_ANOMALY": "Verifier les relations producteur-consommateur et les changements de topologie.",
    "GRAPH_GDN_ANOMALY": "Analyser les noeuds et aretes responsables de la deviation graphe.",
    "GRAPH_MTAD_GAT_ANOMALY": "Verifier la propagation temporelle entre dependances du graphe.",
    "GRAPH_TOPOLOGY_ANOMALY": "Verifier les changements de topologie ou de centralite du graphe.",
    "SECURITY_FAILURE_BURST": "Renforcer la surveillance par adresse IP et acteur, puis verifier les politiques d'acces.",
    "ML_ISOLATION_FOREST": "Comparer l'evenement avec l'historique du flux et verifier les causes de l'ecart detecte par le modele ML.",
    "ML_ONE_CLASS_SVM": "Verifier pourquoi l'appel sort de la frontiere de comportement normal apprise par le modele One-Class SVM.",
    "ML_RANDOM_FOREST": "Verifier la classe d'incident predite par Random Forest et comparer avec les logs du flux concerne.",
    "ML_KMEANS_CLUSTER": "Comparer l'appel avec les profils de clusters habituels et verifier la cause de son eloignement statistique.",
    "ML_AUTOENCODER": "Analyser les variables responsables de l'erreur de reconstruction et comparer l'appel avec les patterns normaux appris.",
    "DL_GRU_SEQUENCE": "Analyser la sequence recente de latence du flux et verifier les causes de l'ecart temporel predit par le modele GRU.",
    "cascade_failure": "Traiter la dependance amont et identifier les flows propages en priorite.",
    "dependent_service_failure": "Verifier le service dependant et ses erreurs recentes.",
    "multi_consumer_impact": "Identifier les consommateurs touches et coordonner la communication incident.",
    "shared_provider_failure": "Notifier l'equipe du producteur partage et isoler les flows critiques.",
    "dependency_hotspot": "Evaluer la charge du producteur central et les risques de saturation.",
    "interoperability_degradation": "Verifier les contrats, SLA et dependances entre systemes GISRE.",
}


class RecommendationService:
    def recommendation_for(self, anomaly_type: str) -> str:
        return RECOMMENDATIONS.get(anomaly_type, "Analyser le contexte technique et confirmer l'incident avec l'equipe responsable.")
